### PR TITLE
Firechat

### PR DESCRIPTION
**Pull request by Sabotnik**
Added script and set it up identical to their 5 min quick setup
Did some CSS stuff too on game show page

### CODE REVIEW

**Comment by Matt-Lepley** [comment]
Game show page css is not displaying the checker effect. I assume it is because you commented out the import of games.. I don't know why that got commented.

**Comment by Sabotnik** [comment]
I had commented it out for a bit because it was interfering with the index page CSS and I didn't think of how to make it not interfere. Fixed it so now game show page has different header and nav classes. Doesn't interfere with index now.

**Comment by Sabotnik** [comment]
added the links from index page just for the sake of having some actual links
added background color to section on game show page

**Comment by Sabotnik** [comment]
Found a better version of firechat that suits our needs better
CSS probably needs some cleaning - was copied
I re-formatted so that CSS is readable at least and deleted the <aside> tag along with CSS for it

**Comment by Sabotnik** [comment]
Paired with @donsalvadori - CSS is now consistent with index styling

**Pull request merged**
