### PR TITLE
finished bishop and rook class

### PR DESCRIPTION
**Pull request by donsalvadori**
I moved the in_bounds? method into pieces class because this will happen for all pieces, and also I think we will be handling the actual move definition within the pieces class as well.

Please leave comments or suggestions.

### CODE REVIEW

**Comment by Matt-Lepley** [comment]
Why did you remove is_obstructed? from the piece class?

**Comment by donsalvadori** [comment]
Hey Matt,

I wasn't sure if that would cause an error/merge conflict. I had the old convoluted one in my bishop branch so I deleted it

**Comment by donsalvadori** [comment]
Matt, I thought that since this was a separate branch from the master it would merge automatically with the new refactored code in the pieces class Isiah did. Please correct me if Im wrong and ill submit a new request today.

**Comment by Matt-Lepley** [comment]
Currently you have 4 merge conflicts. One in each file that you edited since you did not do it on the current master branch or because you manually removed the code from the files. When each branch contains a different version of a file a conflict is raised.

**Comment by donsalvadori** [comment]
Alright Ill fix this when I get home this afternoon. Sorry for the
confusion.

**Pull request merged**
